#!/bin/bash

XCodeRoot=`xcode-select -print-path`
SDKVersion='6.0'
SRCRoot=`pwd`

if [ ! -d $XCodeRoot ]
then
    echo 'buildfailed:Cant found XCode.'
    exit -1
fi

LIPO=$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/usr/bin/lipo'

cd ffmpeg
echo 'build armv7 libs'
make clean
./configure \
--cc=$XCodeRoot/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc \
--as=$SRCRoot'/gas-preprocessor.pl '$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' \
--sysroot=$XCodeRoot/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$SDKVersion.sdk \
--target-os=darwin \
--arch=arm \
--cpu=cortex-a8 \
--extra-cflags='-arch armv7 -I'$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk/usr/include' \
--extra-ldflags='-arch armv7 -isysroot '$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk -L'$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk/usr/lib' \
--prefix=compiled/armv7 \
--enable-cross-compile \
--enable-nonfree \
--enable-gpl \
--disable-armv5te \
--disable-swscale-alpha \
--disable-doc \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-ffserver \
--disable-asm \
--disable-debug

make && make install

echo 'build armv7s libs'
make clean
./configure \
--cc=$XCodeRoot/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc \
--as=$SRCRoot'/gas-preprocessor.pl '$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' \
--sysroot=$XCodeRoot/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$SDKVersion.sdk \
--target-os=darwin \
--arch=arm \
--cpu=cortex-a8 \
--extra-cflags='-arch armv7s -I'$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk/usr/include' \
--extra-ldflags='-arch armv7s -isysroot '$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk -L'$XCodeRoot'/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk/usr/lib' \
--prefix=compiled/armv7s \
--enable-cross-compile \
--enable-nonfree \
--enable-gpl \
--disable-armv5te \
--disable-swscale-alpha \
--disable-doc \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-ffserver \
--disable-asm \
--disable-debug

make && make install

echo 'build i386 libs'
make clean
./configure \
--cc=$XCodeRoot/Platforms/iPhoneSimulator.platform/Developer/usr/bin/gcc \
--as=$SRCRoot'/gas-preprocessor.pl '$XCodeRoot'/Platforms/iPhoneSimulator/Developer/usr/bin/gcc' \
--sysroot=$XCodeRoot/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator$SDKVersion.sdk \
--target-os=darwin \
--arch=i386 \
--cpu=i386 \
--extra-cflags='-arch i386 -I'$XCodeRoot'/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneOS'$SDKVersion'.sdk/usr/include' \
--extra-ldflags='-arch i386 -isysroot '$XCodeRoot'/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator'$SDKVersion'.sdk -L'$XCodeRoot'/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator'$SDKVersion'.sdk/usr/lib' \
--prefix=compiled/i386 \
--enable-cross-compile \
--enable-nonfree \
--enable-gpl \
--disable-armv5te \
--disable-swscale-alpha \
--disable-doc \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-ffserver \
--disable-asm \
--disable-debug

make && make install

echo 'Create universal libs'
mkdir -p ./compiled/fat/lib

$LIPO -output ./compiled/fat/lib/libavcodec.a -create \
-arch armv7 ./compiled/armv7/lib/libavcodec.a \
-arch armv7s ./compiled/armv7s/lib/libavcodec.a \
-arch i386 ./compiled/i386/lib/libavcodec.a

$LIPO -output ./compiled/fat/lib/libavdevice.a -create \
-arch armv7 ./compiled/armv7/lib/libavdevice.a \
-arch armv7s ./compiled/armv7s/lib/libavdevice.a \
-arch i386 ./compiled/i386/lib/libavdevice.a

$LIPO -output ./compiled/fat/lib/libavformat.a -create \
-arch armv7 ./compiled/armv7/lib/libavformat.a \
-arch armv7s ./compiled/armv7s/lib/libavformat.a \
-arch i386 ./compiled/i386/lib/libavformat.a

$LIPO -output ./compiled/fat/lib/libavutil.a -create \
-arch armv7 ./compiled/armv7/lib/libavutil.a \
-arch armv7s ./compiled/armv7s/lib/libavutil.a \
-arch i386 ./compiled/i386/lib/libavutil.a

$LIPO -output ./compiled/fat/lib/libswresample.a -create \
-arch armv7 ./compiled/armv7/lib/libswresample.a \
-arch armv7s ./compiled/armv7s/lib/libswresample.a \
-arch i386 ./compiled/i386/lib/libswresample.a

$LIPO -output ./compiled/fat/lib/libpostproc.a -create \
-arch armv7 ./compiled/armv7/lib/libpostproc.a \
-arch armv7s ./compiled/armv7s/lib/libpostproc.a \
-arch i386 ./compiled/i386/lib/libpostproc.a

$LIPO -output ./compiled/fat/lib/libswscale.a -create \
-arch armv7 ./compiled/armv7/lib/libswscale.a \
-arch armv7s ./compiled/armv7s/lib/libswscale.a \
-arch i386 ./compiled/i386/lib/libswscale.a

$LIPO -output ./compiled/fat/lib/libavfilter.a -create \
-arch armv7 ./compiled/armv7/lib/libavfilter.a \
-arch armv7s ./compiled/armv7s/lib/libavfilter.a \
-arch i386 ./compiled/i386/lib/libavfilter.a

cd $SRCRoot
